builds:
  - builder: prebuilt
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
    goamd64:
      - v1
    prebuilt:
      path: "{{ .Os }}/testkube_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/kubectl-testkube{{ .Ext }}"
    binary: kubectl-testkube
dockers:
  -
    dockerfile: goreleaser.dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-api-server:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=TOKEN=${{.Env.GITHUB_TOKEN}}"
      - "--build-arg=VERSION=${{.Version}}"
      - "--build-arg=COMMIT=${{.Commit}}"
      - "--build-arg=ANALYTICS_TRACKING_ID=${{.Env.ANALYTICS_TRACKING_ID}}"
      - "--build-arg=ANALYTICS_API_KEY=${{.Env.ANALYTICS_API_KEY}}"
      - "--build-arg=SLACK_BOT_CLIENT_ID=${{.Env.SLACK_BOT_CLIENT_ID}}"
      - "--build-arg=SLACK_BOT_CLIENT_SECRET=${{.Env.SLACK_BOT_CLIENT_SECRET}}"
      - "--build-arg=SEGMENTIO_KEY=${{.Env.SEGMENTIO_KEY}}"
  -
    dockerfile: goreleaser.dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "kubeshop/testkube-api-server:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=TOKEN=${{.Env.GITHUB_TOKEN}}"
      - "--build-arg=VERSION=${{.Version}}"
      - "--build-arg=COMMIT=${{.Commit}}"
      - "--build-arg=ANALYTICS_TRACKING_ID=${{.Env.ANALYTICS_TRACKING_ID}}"
      - "--build-arg=ANALYTICS_API_KEY=${{.Env.ANALYTICS_API_KEY}}"
      - "--build-arg=SLACK_BOT_CLIENT_ID=${{.Env.SLACK_BOT_CLIENT_ID}}"
      - "--build-arg=SLACK_BOT_CLIENT_SECRET=${{.Env.SLACK_BOT_CLIENT_SECRET}}"
      - "--build-arg=SEGMENTIO_KEY=${{.Env.SEGMENTIO_KEY}}"
docker_manifests:
  - name_template: kubeshop/testkube-api-server:{{ .Tag }}
    image_templates:
      - kubeshop/testkube-api-server:{{ .Tag }}-amd64
      - kubeshop/testkube-api-server:{{ .Tag }}-arm64
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  # Create a thread in the General category in the repo's discussion tab.
  discussion_category_name: General

  # Tags that have the format v1.0.0-rc1 will mark the release as a pre-release (i.e. not ready for production)
  # Other tags will be marked as ready for production
  prerelease: auto

brews:
  - tap:
      owner: kubeshop
      name: homebrew-testkube-dev
    description: Testkube - your somewhat opinionated and friendly Kubernetes testing framework!
    homepage: https://testkube.io
    license: "MIT"
    dependencies:
      - name: helm
      - name: kubectl
    install: |
      bin.install "kubectl-testkube"
      ln_s bin/"kubectl-testkube", bin/"tk"
      ln_s bin/"kubectl-testkube", bin/"testkube"

nfpms:
  - maintainer: Testkube team
    license: "MIT"
    formats:
      - deb
