apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-webserver
  labels:
    app: debug-webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debug-webserver
  template:
    metadata:
      labels:
        app: debug-webserver
    spec:
      containers:
        - name: debug-webserver
          image: ex00/debug-webserver:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: debug-service
spec:
  type: NodePort
  selector:
    app: debug-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: debug-webserver-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: debug-service
            port:
              number: 80