builds:
  - id: "linux"
    main: "./contrib/executor/{{ .Env.EXECUTOR }}/cmd/agent"
    binary: "{{ .Env.EXECUTOR }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
dockers:
  - dockerfile: "./contrib/executor/{{ .Env.EXECUTOR }}/build/agent/Dockerfile.{{ .Env.EXECUTOR_VERSION }}"
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-{{ .Env.EXECUTOR }}:{{ .Version }}-{{ .Env.EXECUTOR_VERSION }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date}}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--build-arg=TOKEN={{ .Env.TOKEN }}"

  - dockerfile: "./contrib/executor/{{ .Env.EXECUTOR }}/build/agent/Dockerfile.{{ .Env.EXECUTOR_VERSION }}"
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "kubeshop/testkube-{{ .Env.EXECUTOR }}:{{ .Version }}-{{ .Env.EXECUTOR_VERSION }}-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--build-arg=TOKEN={{ .Env.TOKEN }}"

  - dockerfile: "./contrib/executor/{{ .Env.EXECUTOR }}/build/agent/Dockerfile.jdk11"
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-{{ .Env.EXECUTOR }}:{{ .Version }}-amd64"
      - "kubeshop/testkube-{{ .Env.EXECUTOR }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date}}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--build-arg=TOKEN={{ .Env.TOKEN }}"

  - dockerfile: "./contrib/executor/{{ .Env.EXECUTOR }}/build/agent/Dockerfile.jdk11"
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "kubeshop/testkube-{{ .Env.EXECUTOR }}:{{ .Version }}-arm64v8"
      - "kubeshop/testkube-{{ .Env.EXECUTOR }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--build-arg=TOKEN={{ .Env.TOKEN }}"

#  - dockerfile: "./contrib/executor/{{ .Env.EXECUTOR }}/build/agent/Dockerfile.jdk17"
#    use: buildx
#    goos: linux
#    goarch: amd64
#    image_templates:
#      - "kubeshop/testkube-{{ .Env.EXECUTOR }}:{{ .Version }}-jdk17-amd64"
#    build_flag_templates:
#      - "--platform=linux/amd64"
#      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
#      - "--label=org.opencontainers.image.created={{ .Date}}"
#      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
#      - "--build-arg=TOKEN={{ .Env.TOKEN }}"
#
#  - dockerfile: "./contrib/executor/{{ .Env.EXECUTOR }}/build/agent/Dockerfile.jdk17"
#    use: buildx
#    goos: linux
#    goarch: arm64
#    image_templates:
#      - "kubeshop/testkube-{{ .Env.EXECUTOR }}:{{ .Version }}-jdk17-arm64v8"
#    build_flag_templates:
#      - "--platform=linux/arm64/v8"
#      - "--label=org.opencontainers.image.created={{ .Date }}"
#      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
#      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
#      - "--build-arg=TOKEN={{ .Env.TOKEN }}"

#  - dockerfile: "./contrib/executor/{{ .Env.EXECUTOR }}/build/agent/Dockerfile.jdk18"
#    use: buildx
#    goos: linux
#    goarch: amd64
#    image_templates:
#      - "kubeshop/testkube-{{ .Env.EXECUTOR }}:{{ .Version }}-jdk18-amd64"
#    build_flag_templates:
#      - "--platform=linux/amd64"
#      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
#      - "--label=org.opencontainers.image.created={{ .Date}}"
#      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
#      - "--build-arg=TOKEN={{ .Env.TOKEN }}"
#
#  - dockerfile: "./contrib/executor/{{ .Env.EXECUTOR }}/build/agent/Dockerfile.jdk18"
#    use: buildx
#    goos: linux
#    goarch: arm64
#    image_templates:
#      - "kubeshop/testkube-{{ .Env.EXECUTOR }}:{{ .Version }}-jdk18-arm64v8"
#    build_flag_templates:
#      - "--platform=linux/arm64/v8"
#      - "--label=org.opencontainers.image.created={{ .Date }}"
#      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
#      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
#      - "--build-arg=TOKEN={{ .Env.TOKEN }}"

docker_manifests:
  - name_template: kubeshop/testkube-{{ .Env.EXECUTOR }}:{{ .Version }}-{{ .Env.EXECUTOR_VERSION }}
    image_templates:
      - kubeshop/testkube-{{ .Env.EXECUTOR }}:{{ .Version }}-{{ .Env.EXECUTOR_VERSION }}-amd64
      - kubeshop/testkube-{{ .Env.EXECUTOR }}:{{ .Version }}-{{ .Env.EXECUTOR_VERSION }}-arm64v8
  - name_template: kubeshop/testkube-{{ .Env.EXECUTOR }}:latest
    image_templates:
      - kubeshop/testkube-{{ .Env.EXECUTOR }}:latest-amd64
      - kubeshop/testkube-{{ .Env.EXECUTOR }}:latest-arm64v8
