name: Docker images building and pushing for jdk executor
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  docker:
    strategy:
      matrix:
      # version: [default, jdk8, jdk11, jdk17,jdk18]
      # executor: [gradle, maven]
        version: [default]
        executor: [gradle]     

    runs-on: ubuntu-latest
    steps:

      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      -
        name: Docker Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Docker meta for ${{ matrix.version }} ${{ matrix.executor }} executor
        if: ${{matrix.version == 'default'}}
        id: meta_executor_default
        uses: docker/metadata-action@v3
        with:
          images: kubeshop/testkube-${{ matrix.executor }}-executor
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
          flavor: |
            latest=auto
            prefix=

      -
        name: Docker meta for ${{ matrix.executor }} executor ${{ matrix.version }}
        if: ${{matrix.version != 'default'}}
        id: meta_executor
        uses: docker/metadata-action@v3
        with:
          images: kubeshop/testkube-${{ matrix.executor }}-executor
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
          flavor: |
            latest=auto
            prefix=
            suffix=-${{ matrix.version }}

      - 
        name: Build ${{ matrix.version }} ${{ matrix.executor }} executor
        if: ${{matrix.version == 'default'}}
        uses: docker/bake-action@v1
        with:
          files: |
            contrib/executor/${{ matrix.executor }}/build/agent/docker-bake.hcl
            ${{ steps.meta_executor_default.outputs.bake-file }}
          targets: jdk11
          set: jdk11.args.TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
          push: true

      -
        name: Build ${{ matrix.executor }} ${{ matrix.executor }} executor
        if: ${{matrix.version != 'default'}}
        uses: docker/bake-action@v1
        with:
          files: |
            contrib/executor/${{ matrix.executor }}/build/agent/docker-bake.hcl
            ${{ steps.meta_executor.outputs.bake-file }}
          targets: ${{ matrix.version }}
          set: ${{ matrix.version }}.args.TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
          push: true