name: Docker images building and pushing for helper executor
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  docker:
    strategy:
      matrix:
        executor: [init, scraper]

    runs-on: ubuntu-latest
    steps:

      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      -
        name: Docker Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Docker meta for ${{ matrix.executor }} executor
        id: meta_executor
        uses: docker/metadata-action@v3
        with:
          images: kubeshop/testkube-executor-${{ matrix.executor }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      -
        name: Build ${{ matrix.executor }} executor
        uses: docker/bake-action@v1
        with:
          files: |
            contrib/executor/${{ matrix.executor }}/build/agent/docker-bake.hcl
            ${{ steps.meta_executor.outputs.bake-file }}
          targets: build
          set: build.args.TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
          push: true